version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

  main:
    container_name: api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    command: yarn start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
networks:
  webnet:
volumes:
  pgdata:
